config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie_id, uniqueness: {scope: :list_id, message: "is already in the list!"}
  validates :comment, length: {minimum: 6}
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container mt-5">
  <h1>Add a new movie to your <%= @list.name %> list</h1>
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie %>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "/assets/application.js", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="wrapper">

  <div class="banner-index">
    <h1>Welcome to your list</h1>
  </div>

  <div class="list-index-content">
    <% @lists.each do |list| %>

      <%= link_to list_path(list) do %>
        <div class="list-card-index">
          <%= image_tag 'list-image', class: 'image-list-cover', alt: "image cover for list" %>

          <div class="list-card-content">
            <p><%= list.name %></p>
          </div>
        </div>
      <% end %>

    <% end %>
  </div>

</div>

app/views/lists/new.html.erb
<%= simple_form_for [@list] do |f| %>
  <%= f.input :name %>
  <%# <%= f.input :photo, as: :file %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/lists/show.html.erb
<div class="wrapper">
  <div class="banner-index">
    <h1><%= @list.name %></div>
  </div>

  <div class="list-index-content">
    <% @list.movies.each do |movie| %>
      <div class="list-card-index">
        <%= image_tag 'list-image', class: 'image-list-cover', alt: "image cover for list" %>
        <div class="list-card-content">
          <p><%= movie.title %></p>
          <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
          <%= link_to 'Delete', bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?", status: :see_other}, class: 'btn btn-danger btn-sm' %>
        </div>
      </div>
    <% end %>

  </div>

  <div class="show-navigate">
    <%= link_to "Home Page", lists_path, class: 'btn btn-success' %>
    <%= link_to "Add a movie", new_list_bookmark_path(@list), class: 'btn btn-primary' %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="logo-navbar">
    <% link_to lists_path do %>
      <%= image_tag "popcorn.jpg", class: 'logo logo-round-shadow', alt: 'app logo' %>
    <% end %>
    <p>MOVIE LIST</p>
  </div>
  <div class="navbar-links">
    <%= link_to "Add a list", new_list_path, class: 'btn btn-primary' %>
  </div>
</div>